"""Action execution framework for the AI Agent HA integration.

This module provides comprehensive action execution capabilities including:
- Single action execution with error handling
- Action simulation (dry run) for validation
- Batch execution with configurable error handling
- Rollback support for failed action sequences
- Execution pipeline orchestration

The action executor integrates with Home Assistant's service registry to
execute service calls generated by the AI agent.
"""

import asyncio
import logging
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.setup import async_get_domains_in_state

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)


@dataclass
class ActionResult:
    """Result of executing an action."""

    action_id: str
    domain: str
    service: str
    target: Dict[str, Any]
    service_data: Dict[str, Any]
    success: bool
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    execution_time: float = 0.0
    rolled_back: bool = False


@dataclass
class SimulatedActionResult:
    """Result of simulating an action (dry run)."""

    action_id: str
    domain: str
    service: str
    target: Dict[str, Any]
    service_data: Dict[str, Any]
    would_succeed: bool
    warnings: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)


class ActionExecutor:
    """Executes actions (service calls) in Home Assistant."""

    def __init__(self, hass: HomeAssistant):
        """Initialize the ActionExecutor.

        Args:
            hass: Home Assistant core instance.
        """
        self.hass = hass

    async def execute_action(
        self, action: Dict[str, Any], action_id: str = ""
    ) -> ActionResult:
        """Execute a single action.

        Args:
            action: Dictionary containing action details with keys:
                - domain: Service domain (e.g., 'light')
                - service: Service name (e.g., 'turn_on')
                - target: Service target (e.g., {'entity_id': 'light.living_room'})
                - service_data: Service data (e.g., {'brightness': 200})
            action_id: Optional action identifier. Generated if empty.

        Returns:
            ActionResult with execution details.
        """
        if not action_id:
            action_id = str(uuid.uuid4())

        domain = action.get("domain", "")
        service = action.get("service", "")
        target = action.get("target", {})
        service_data = action.get("service_data", {})

        start_time = time.time()

        try:
            # Execute the service call
            result = await self.hass.services.async_call(
                domain=domain,
                service=service,
                service_data=service_data,
                target=target,
                blocking=True,
                return_response=True,
            )

            execution_time = time.time() - start_time

            _LOGGER.debug(
                "Action %s executed successfully: %s.%s",
                action_id,
                domain,
                service,
            )

            return ActionResult(
                action_id=action_id,
                domain=domain,
                service=service,
                target=target,
                service_data=service_data,
                success=True,
                result={"response": result} if result else None,
                execution_time=execution_time,
            )

        except Exception as e:
            execution_time = time.time() - start_time
            error_msg = str(e)

            _LOGGER.error(
                "Action %s failed: %s.%s - %s",
                action_id,
                domain,
                service,
                error_msg,
            )

            return ActionResult(
                action_id=action_id,
                domain=domain,
                service=service,
                target=target,
                service_data=service_data,
                success=False,
                error=error_msg,
                execution_time=execution_time,
            )

    async def simulate_action(
        self, action: Dict[str, Any], action_id: str = ""
    ) -> SimulatedActionResult:
        """Simulate an action without actually executing it (dry run).

        Args:
            action: Dictionary containing action details.
            action_id: Optional action identifier. Generated if empty.

        Returns:
            SimulatedActionResult with simulation details.
        """
        if not action_id:
            action_id = str(uuid.uuid4())

        domain = action.get("domain", "")
        service = action.get("service", "")
        target = action.get("target", {})
        service_data = action.get("service_data", {})

        warnings = []
        recommendations = []
        would_succeed = True

        # Validate action structure
        if not domain:
            would_succeed = False
            warnings.append("Missing domain in action")
            recommendations.append("Specify a valid service domain (e.g., 'light', 'switch')")
        elif not service:
            would_succeed = False
            warnings.append("Missing service in action")
            recommendations.append("Specify a valid service name (e.g., 'turn_on', 'turn_off')")

        # Check if domain exists
        if domain and service:
            is_valid, domain_warnings = await self._validate_action_exists(
                domain, service, target.get("entity_id") if target else None
            )
            warnings.extend(domain_warnings)
            if not is_valid:
                would_succeed = False

        # Check if entity exists in target
        entity_id = target.get("entity_id") if target else None
        if entity_id:
            entity_warnings, entity_recommendations = await self._validate_entity_exists(
                entity_id
            )
            warnings.extend(entity_warnings)
            recommendations.extend(entity_recommendations)
            if entity_warnings:
                would_succeed = False

        # Check for common service data issues
        data_warnings = self._validate_service_data(domain, service, service_data)
        warnings.extend(data_warnings)

        # Generate recommendations based on action type
        service_recommendations = self._generate_service_recommendations(
            domain, service, service_data
        )
        recommendations.extend(service_recommendations)

        return SimulatedActionResult(
            action_id=action_id,
            domain=domain,
            service=service,
            target=target,
            service_data=service_data,
            would_succeed=would_succeed,
            warnings=warnings,
            recommendations=recommendations,
        )

    async def execute_batch(
        self,
        actions: List[Dict[str, Any]],
        fail_on_error: bool = True,
    ) -> List[ActionResult]:
        """Execute multiple actions as a batch.

        Args:
            actions: List of action dictionaries to execute.
            fail_on_error: If True, stop on first failure.
                          If False, continue and collect all results.

        Returns:
            List of ActionResult objects.
        """
        results = []

        for i, action in enumerate(actions):
            action_id = action.get("action_id", f"batch_{i}")

            _LOGGER.debug("Executing batch action %d: %s", i, action_id)

            result = await self.execute_action(action, action_id)
            results.append(result)

            if not result.success:
                _LOGGER.warning(
                    "Batch action %s failed: %s", action_id, result.error
                )

                if fail_on_error:
                    _LOGGER.warning("Stopping batch execution due to failure")
                    break

        _LOGGER.info(
            "Batch execution complete: %d/%d actions successful",
            sum(1 for r in results if r.success),
            len(results),
        )

        return results

    async def execute_with_rollback(
        self, actions: List[Dict[str, Any]]
    ) -> Tuple[List[ActionResult], List[ActionResult]]:
        """Execute actions and if any fail, rollback all successful actions.

        Args:
            actions: List of action dictionaries to execute.

        Returns:
            Tuple of (successful_actions, rolled_back_actions).
        """
        successful_actions = []
        rolled_back_actions = []

        # Execute all actions, tracking successful ones
        for i, action in enumerate(actions):
            action_id = action.get("action_id", f"rollback_{i}")

            result = await self.execute_action(action, action_id)
            successful_actions.append(result)

            if not result.success:
                _LOGGER.warning(
                    "Action %s failed, initiating rollback", action_id
                )

                # Rollback all previously successful actions
                for prev_result in successful_actions[:-1]:
                    rollback_action = self._generate_rollback_action(
                        {
                            "domain": prev_result.domain,
                            "service": prev_result.service,
                            "target": prev_result.target,
                            "service_data": prev_result.service_data,
                        }
                    )

                    if rollback_action:
                        rollback_result = await self.execute_action(
                            rollback_action, f"rollback_{prev_result.action_id}"
                        )
                        rollback_result.rolled_back = True
                        rolled_back_actions.append(rollback_result)

                        _LOGGER.info(
                            "Rolled back action: %s.%s",
                            prev_result.domain,
                            prev_result.service,
                        )

                return successful_actions, rolled_back_actions

        # All actions succeeded, no rollback needed
        return successful_actions, rolled_back_actions

    def _generate_rollback_action(
        self, original_action: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]:
        """Generate a rollback action for a given action.

        Args:
            original_action: The original action to rollback.

        Returns:
            Rollback action dictionary, or None if rollback not supported.
        """
        domain = original_action.get("domain", "")
        service = original_action.get("service", "")
        target = original_action.get("target", {})
        service_data = original_action.get("service_data", {})

        # Define rollback mappings
        rollback_mappings = {
            ("light", "turn_on"): ("light", "turn_off"),
            ("light", "turn_off"): ("light", "turn_on"),
            ("switch", "turn_on"): ("switch", "turn_off"),
            ("switch", "turn_off"): ("switch", "turn_on"),
            ("media_player", "pause"): ("media_player", "play"),
            ("media_player", "play"): ("media_player", "pause"),
            ("media_player", "stop"): ("media_player", "play"),
            ("climate", "set_temperature"): ("climate", "set_temperature"),
            ("cover", "open_cover"): ("cover", "close_cover"),
            ("cover", "close_cover"): ("cover", "open_cover"),
            ("valve", "open_valve"): ("valve", "close_valve"),
            ("valve", "close_valve"): ("valve", "open_valve"),
        }

        rollback_key = (domain, service)
        if rollback_key in rollback_mappings:
            rollback_domain, rollback_service = rollback_mappings[rollback_key]
            return {
                "domain": rollback_domain,
                "service": rollback_service,
                "target": target,
                "service_data": service_data,
            }

        # For other services, try to infer rollback
        if domain and service:
            # Generic pattern: turn_on -> turn_off and vice versa
            if service.endswith("_on"):
                rollback_service = service[:-3] + "_off"
                return {
                    "domain": domain,
                    "service": rollback_service,
                    "target": target,
                    "service_data": service_data,
                }
            elif service.endswith("_off"):
                rollback_service = service[:-4] + "_on"
                return {
                    "domain": domain,
                    "service": rollback_service,
                    "target": target,
                    "service_data": service_data,
                }

        _LOGGER.warning(
            "No rollback action defined for %s.%s", domain, service
        )
        return None

    async def _validate_action_exists(
        self,
        domain: str,
        service: str,
        entity_id: str = None,
    ) -> Tuple[bool, List[str]]:
        """Validate that the domain, service, and entity exist.

        Args:
            domain: Service domain to validate.
            service: Service name to validate.
            entity_id: Optional entity ID to validate.

        Returns:
            Tuple of (is_valid, warnings).
        """
        warnings = []

        # Check if domain exists
        domains = async_get_domains_in_state(self.hass)
        if domain not in domains and domain != "persistent_notification":
            # Domain might not be loaded yet, but service could still exist
            try:
                services = list(self.hass.services.async_services())
                if domain not in services:
                    warnings.append(
                        f"Domain '{domain}' may not be loaded or does not exist"
                    )
            except Exception:
                warnings.append(f"Unable to verify domain '{domain}'")

        # Check if service exists in domain
        try:
            services = self.hass.services.async_services()
            if domain in services:
                if service not in services[domain]:
                    warnings.append(
                        f"Service '{domain}.{service}' does not exist"
                    )
            else:
                # Domain not in services yet
                pass
        except Exception as e:
            warnings.append(f"Error checking service: {e}")

        # Check entity if provided
        if entity_id:
            entity = self.hass.states.get(entity_id)
            if not entity:
                warnings.append(f"Entity '{entity_id}' does not exist")

        is_valid = len(warnings) == 0
        return is_valid, warnings

    async def _validate_entity_exists(
        self, entity_id: str
    ) -> Tuple[List[str], List[str]]:
        """Validate that an entity exists.

        Args:
            entity_id: Entity ID to validate.

        Returns:
            Tuple of (warnings, recommendations).
        """
        warnings = []
        recommendations = []

        entity = self.hass.states.get(entity_id)
        if not entity:
            warnings.append(f"Entity '{entity_id}' does not exist")
            recommendations.append(
                f"Verify the entity ID '{entity_id}' is correct"
            )

            # Suggest similar entities
            similar = self._find_similar_entities(entity_id)
            if similar:
                recommendations.append(
                    f"Did you mean: {', '.join(similar[:3])}"
                )

        return warnings, recommendations

    def _find_similar_entities(
        self, entity_id: str, max_results: int = 3
    ) -> List[str]:
        """Find similar entity IDs.

        Args:
            entity_id: The entity ID to find similar matches for.
            max_results: Maximum number of results to return.

        Returns:
            List of similar entity IDs.
        """
        all_states = self.hass.states.async_all()
        all_entity_ids = [state.entity_id for state in all_states]

        # Simple similarity: check if entity_id is a substring or vice versa
        similar = []
        for eid in all_entity_ids:
            if (
                entity_id in eid
                or eid in entity_id
                or entity_id.replace(".", "").replace("_", "")
                in eid.replace(".", "").replace("_", "")
            ):
                similar.append(eid)
                if len(similar) >= max_results:
                    break

        return similar

    def _validate_service_data(
        self,
        domain: str,
        service: str,
        service_data: Dict[str, Any],
    ) -> List[str]:
        """Validate service data for common issues.

        Args:
            domain: Service domain.
            service: Service name.
            service_data: Service data to validate.

        Returns:
            List of warnings.
        """
        warnings = []

        if not service_data:
            return warnings

        # Check for empty service data
        if not service_data:
            warnings.append("Empty service data")

        # Check for common issues
        if domain == "light" and service == "turn_on":
            brightness = service_data.get("brightness")
            if brightness and (brightness < 0 or brightness > 255):
                warnings.append(
                    "Brightness value should be between 0 and 255"
                )

            color_temp = service_data.get("color_temp")
            if color_temp and (color_temp < 153 or color_temp > 500):
                warnings.append(
                    "Color temperature should be between 153 and 500 mireds"
                )

        elif domain == "climate" and service == "set_temperature":
            temperature = service_data.get("temperature")
            if temperature:
                hvac_mode = service_data.get("hvac_mode")
                if hvac_mode and temperature:
                    if hvac_mode == "cool" and temperature < 16:
                        warnings.append(
                            "Cooling temperature below recommended minimum (16°C)"
                        )
                    elif hvac_mode == "heat" and temperature > 30:
                        warnings.append(
                            "Heating temperature above recommended maximum (30°C)"
                        )

        return warnings

    def _generate_service_recommendations(
        self,
        domain: str,
        service: str,
        service_data: Dict[str, Any],
    ) -> List[str]:
        """Generate recommendations for a service call.

        Args:
            domain: Service domain.
            service: Service name.
            service_data: Service data.

        Returns:
            List of recommendations.
        """
        recommendations = []

        if domain == "light" and service == "turn_on":
            if not service_data.get("brightness") and not service_data.get(
                "rgb_color"
            ):
                recommendations.append(
                    "Consider setting brightness for better control"
                )

        elif domain == "media_player" and service == "volume_set":
            volume = service_data.get("volume_level")
            if volume and volume > 0.9:
                recommendations.append(
                    "Volume level is very high, consider reducing"
                )

        elif domain == "script" and service == "turn_on":
            recommendations.append(
                "Consider using 'script.turn_on' with 'stop_actions' for safety"
            )

        return recommendations


class ActionExecutionPipeline:
    """Orchestrates the full action execution pipeline."""

    def __init__(
        self, hass: HomeAssistant, simulate_first: bool = False
    ):
        """Initialize the ActionExecutionPipeline.

        Args:
            hass: Home Assistant core instance.
            simulate_first: If True, simulate actions before execution.
        """
        self.hass = hass
        self.simulate_first = simulate_first
        self.executor = ActionExecutor(hass)

    async def execute_pipeline(
        self,
        actions: List[Dict[str, Any]],
        simulation_report: Optional[Dict] = None,
    ) -> Tuple[List[ActionResult], List[SimulatedActionResult]]:
        """Execute the full pipeline.

        Pipeline steps:
        1. If simulate_first is True, simulate all actions first
        2. Execute actions (with rollback if configured)
        3. Return (results, simulations)

        Args:
            actions: List of action dictionaries to execute.
            simulation_report: Optional pre-computed simulation report.

        Returns:
            Tuple of (results, simulations).
        """
        simulations = []

        # Step 1: Simulate actions if enabled
        if self.simulate_first and not simulation_report:
            for i, action in enumerate(actions):
                action_id = action.get("action_id", f"pipeline_{i}")
                simulation = await self.executor.simulate_action(
                    action, action_id
                )
                simulations.append(simulation)

            # Check simulation results
            failed_simulations = [
                s for s in simulations if not s.would_succeed
            ]
            if failed_simulations:
                _LOGGER.warning(
                    "%d out of %d actions failed simulation",
                    len(failed_simulations),
                    len(simulations),
                )

                for sim in failed_simulations:
                    _LOGGER.warning(
                        "Action %s.%s warnings: %s",
                        sim.domain,
                        sim.service,
                        sim.warnings,
                    )

        elif simulation_report:
            # Use pre-computed simulation report
            simulations = simulation_report.get("simulations", [])

        # Step 2: Execute actions
        results = await self.executor.execute_batch(actions, fail_on_error=True)

        _LOGGER.info(
            "Pipeline execution complete: %d/%d actions successful",
            sum(1 for r in results if r.success),
            len(results),
        )

        return results, simulations


# Module-level cache for singleton pattern
_executor_cache: Dict[int, ActionExecutionPipeline] = {}


def get_action_executor(
    hass: HomeAssistant, simulate_first: bool = False
) -> ActionExecutionPipeline:
    """Get or create ActionExecutionPipeline singleton.

    Args:
        hass: Home Assistant core instance.
        simulate_first: If True, simulate actions before execution.

    Returns:
        ActionExecutionPipeline instance.
    """
    hass_id = id(hass)

    if hass_id not in _executor_cache:
        _executor_cache[hass_id] = ActionExecutionPipeline(
            hass, simulate_first
        )
    else:
        # Update simulate_first setting if needed
        pipeline = _executor_cache[hass_id]
        pipeline.simulate_first = simulate_first

    return _executor_cache[hass_id]
